
ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                                                                      บ
บ   ( '>')  Tiny Core is distributed with ABSOLUTELY NO WARRANTY.      บ
บ  /) TC (\          A Busybox & Fltk minimal desktop.                 บ
บ (/-_--_-\)              www.tinycorelinux.net                        บ
บ                                                                      บ
บ                        Version 6.4                                   บ
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

Welcome to Tiny Core Plus. This is a collection of extensions
to help get started with Tiny Core Linux. It is not intended to be a 
replacement for distribution.

Booting from this CD will first load your regular extensions (if any),
then load the additional extensions for installation, networking, and 
remastering.

Press <Enter> for Tiny Core Plus 
Or Press F2, F3, or F4 to view additional boot options, F1 returns here.

