
ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                                                                      บ
บ   ( '>') oVirt Tiny Core is distributed with ABSOLUTELY NO WARRANTY. บ
บ  /)oVTC(\          A Busybox & Fltk minimal desktop.                 บ
บ (/-_--_-\)    Based on Tiny Core Linux - www.tinycorelinux.net       บ
บ                                                                      บ
บ oVirt customization by Lev Veyde <lveyde@redhat.com> - Version 13.7  บ
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

Welcome to oVirt Tiny Core. This is a collection of extensions
to help get started with Tiny Core Linux. It is not intended to be a 
replacement for distribution.

Booting from this CD will first load your regular extensions (if any),
then load the additional extensions for installation, networking, and 
remastering.

Press <Enter> for oVirt Tiny Core
Or Press F2, F3, or F4 to view additional boot options, F1 returns here.

